sudo: required
language: python

python:
  - "3.6"

services: 
  - postgresql

env:
  - DJANGO_VERSION=2.1.3

install:
  - pip install -r requirements.txt
  - pip install selenium

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar -xvzf geckodriver*
  - chmod +x geckodriver
  - sudo mv geckodriver /usr/local/bin/

script:
  - ./manage.py test
