sudo: required
language: python

python:
  - "3.6"

services: 
  - postgresql

env:
  - DJANGO_VERSION=2.1.3

addons:
  firefox: latest

install:
  

before_install:
  # Required to run browser tests (FF) ##
  - ./setup_geckodriver.sh
  - export PATH="${HOME}/geckodriver:${PATH}"

install:
  - make run-web-app
  - pip install -r requirements.txt
  - pip install selenium

script:
  - ./manage.py test
