sudo: required
language: python

python:
  - "3.6"

services: 
  - postgresql

env:
  - DJANGO_VERSION=2.1.3

addons:
  firefox: "45.4.0esr"

install:
  - pip install -r requirements.txt
  - pip install selenium

before_script:
  # Required to run browser tests (FF) ##
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - ./manage.py test
