sudo: required
language: python

python:
  - "3.6"

services: 
  - postgresql

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

before_install:
  # Required to run browser tests (FF) ##
  - ./setup_geckodriver.sh
  - export PATH="${HOME}/geckodriver:${PATH}"

install:
  - pip install -r requirements.txt
  - pip install selenium

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./manage.py test --settings=pur_beurre_django_app.settings
