sudo: required
language: python

python:
  - "3.6"

services: 
  - postgresql

env:
  - DJANGO_VERSION=2.1.3

addons:
  firefox: lastest

install:
  - pip install -r requirements.txt
  - pip install selenium

before_script:
  # Required to run browser tests (FF) ##
  - ./setup_geckodriver.sh
  - export PATH="${HOME}/geckodriver:${PATH}"

script:
  - ./manage.py test
